### PR TITLE
Fix Tests

### PR DESCRIPTION
**Pull request by kunicmarko20**
Not sure how is the build even passing, tests had the wrong namespace :man_shrugging:

### CODE REVIEW

**Comment by greg0ire** [comment]
> Not sure how is the build even passing

Now it isn't :sweat_smile:

**Comment by greg0ire** [comment]
> Not sure how is the build even passing

Now it isn't :sweat_smile: 

>  tests had the wrong namespace

phpunit does not care about the namespaces of the test class at all, that's why :P

**Comment by kunicmarko20** [comment]
blocked by #239

**Comment by kunicmarko20** [comment]
This should be done

**Pull request merged**
