### PR TITLE
Don't merge, just testing

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
> PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
>
> Warning: Xdebug MUST be loaded as a Zend extension in Unknown on line 0

**Comment by greg0ire** [comment]
Doesn't work with `config-add` either.

**Comment by Soullivaneuh** [comment]
This is strange because I did this for my project: https://github.com/Soullivaneuh/IsoCodesValidator/blob/946e3cd87f1839d82f045867e40b8ec9f14ce176/.travis.yml#L51

And it works: https://travis-ci.org/Soullivaneuh/IsoCodesValidator/jobs/125869361#L395

**Comment by greg0ire** [comment]
Backup / restore it is!

**Pull request closed without merging**
