### PR TITLE
Allow magic _call for DoctrineORMQuerySourceIterator

### PR DESCRIPTION
**Pull request by webda2l**
In the same idea of https://github.com/sonata-project/SonataAdminBundle/pull/2262, extend usability
See http://a2lix.fr/blog/2014/08/04/translate-internationalize-doctrine-entities-sonata.html

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@webda2l Could you please rebase your PR?

@rande What you you think about it? Should be accepted? I would like to resolve it for version bumping (#47).

**Comment by Soullivaneuh** [comment]
@webda2l And as well, can you explain your modifications on the changelog?

**Comment by rande** [comment]
The tests are missing. Yes we can merge it once this will be ready

**Comment by Soullivaneuh** [comment]
Well, @webda2l there is the todo list to get this PR accepted:

 * Rebased PR
 * Adding line note on changelog
 * Update / make related tests
 * Squashing commits

Please ping me when it's done. :+1: 

Thanks.

**Comment by core23** [comment]
@webda2l Are you still working on this?

**Comment by webda2l** [comment]
@core23 No, busy currently, feel free to continue

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
