### PR TITLE
DevKit updates for master branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire can you help?

**Comment by greg0ire** [comment]
Restarting travis, but it seems mongo is missing.

**Comment by OskarStark** [comment]
still a problem @greg0ire , how to proceed?

**Comment by greg0ire** [comment]
Find out why mongo is missing… have a look at the last travis.yml changes?

**Comment by greg0ire** [comment]
@OskarStark maybe this is the reason: https://github.com/sonata-project/dev-kit/blob/d97e753e0bf5df071b344705f7115905b77c15b6/project/.travis/before_install_test.sh.twig#L9

**Comment by greg0ire** [comment]
Might be solved by https://github.com/sonata-project/dev-kit/pull/238/files

**Comment by OskarStark** [comment]
sounds reasonable, so we should merge: https://github.com/sonata-project/dev-kit/pull/238

**Pull request merged**
