### PR TITLE
Advertise export formats

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is backwards-compatible

## Changelog

```markdown
### Added
- Added some `Exporter::getAvailableFormats` to retrieve the list of the formats of the registered writers
```

## To do

Nothing, I hope

## Subject

I'd like to make the admin bundle more flexible about exports, and this method should allow us to have the export formats list nicely update each time we add a new writer.

### CODE REVIEW

**Comment by OskarStark** [comment]
LGTM 👍 

`minor` i guess

**Comment by greg0ire** [comment]
Good guess : the API gets a new element :)

**Comment by greg0ire** [comment]
@core23 , final review and merge?

**Comment by greg0ire** [comment]
ping @sonata-project/contributors

**Comment by OskarStark** [comment]
Thank you @greg0ire 👍

**Pull request merged**
