### PR TITLE
Replace boolean's value by yes/no

### PR DESCRIPTION
**Pull request by chalasr**
I am working on a sonata project and I had to export datas.
All yes/no questions in my forms are stored as boolean, but on export sonata is returning boolean.
Maybe exist more simple alternative in front of Sonata Admin ?

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
It's totally normal to have booleans on exported data.

BTW, your PR will be completely BC break.

At least, if you really want it, you could propose it as an option.

**Comment by OskarStark** [comment]
i like this PR, we should merge this in a new major IMO

ping @rande

**Comment by chalasr** [comment]
Maybe it's a better idea to propose it as an exporter optional config for admin class,

**Comment by chalasr** [comment]
I will propose it as an exporter optional configuration for admin class, as stated by @Soullivaneuh

**Comment by fre5h** [comment]
Don't forget to add translator inside DoctrineORMQuerySourceIterator to allow automatically translation of `yes` and `no` values.

**Comment by OskarStark** [comment]
i think this should be done before, shouldn't it?

**Comment by fre5h** [comment]
What exactly? In this PR boolean values come from entities and are change to yes/no values inside DoctrineORMQuerySourceIterator.

**Pull request closed without merging**
