### PR TITLE
DevKit updates for 1.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by core23** [comment]
@greg0ire Can you have a look at this?

**Comment by greg0ire** [comment]
@core23 you mean can I have a look at the ODM build, which I asked for help about on Slack? Uuuuh sure 😅

**Comment by core23** [comment]
Oh, sorry. I'm not that active on slack 😅 

Thought the bug was introduced by the `dev-master as ` changes

**Comment by greg0ire** [comment]
No worries ;) I'm trying things I see here: https://github.com/doctrine/mongodb/blob/master/.travis.yml

**Comment by greg0ire** [comment]
Tried many things, to no avail... halp!

**Comment by greg0ire** [comment]
Oh I just noticed the reason: https://travis-ci.org/sonata-project/exporter/jobs/299285972#L690

**Comment by greg0ire** [comment]
Tried moar things, looks good :)

**Pull request merged**
